font_family JetBrains Mono
font_size 12.0

background #000000
foreground #e6e6e6

selection_background #ffffff
selection_foreground #000000

cursor #ffffff
cursor_text_color #000000
cursor_shape beam
cursor_blink_interval 0

background_opacity 0.88
dynamic_background_opacity yes

window_padding_width 10
hide_window_decorations yes

enable_audio_bell no
visual_bell_duration 0.0
window_alert_on_bell no

scrollback_lines 10000
wheel_scroll_multiplier 3.0

copy_on_select yes
strip_trailing_spaces smart

tab_bar_edge bottom
tab_bar_style separator
active_tab_foreground #000000
active_tab_background #ffffff
inactive_tab_foreground #aaaaaa
inactive_tab_background #111111

confirm_os_window_close 0

color0  #000000
color1  #777777
color2  #999999
color3  #aaaaaa
color4  #bbbbbb
color5  #cccccc
color6  #dddddd
color7  #eeeeee

color8  #444444
color9  #888888
color10 #aaaaaa
color11 #bbbbbb
color12 #cccccc
color13 #dddddd
color14 #eeeeee
color15 #ffffff
